/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Employee = IDL.Record({
  'name' : IDL.Text,
  'designation' : IDL.Text,
  'joiningDate' : IDL.Text,
  'totalLeaveBalance' : IDL.Nat,
  'email' : IDL.Text,
  'leavesTaken' : IDL.Nat,
  'employeeId' : IDL.Text,
  'linkedUserId' : IDL.Opt(IDL.Text),
  'bonus' : IDL.Float64,
  'department' : IDL.Text,
  'baseSalary' : IDL.Float64,
  'pfPercentage' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const LeaveStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const LeaveRequest = IDL.Record({
  'status' : LeaveStatus,
  'leaveId' : IDL.Text,
  'employeeName' : IDL.Text,
  'endDate' : IDL.Text,
  'days' : IDL.Nat,
  'submittedOn' : IDL.Text,
  'employeeId' : IDL.Text,
  'startDate' : IDL.Text,
  'reason' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'employeeId' : IDL.Opt(IDL.Text),
});
export const ContactSubmission = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'submittedOn' : IDL.Text,
  'email' : IDL.Text,
  'company' : IDL.Text,
  'message' : IDL.Text,
});
export const SalaryBreakdown = IDL.Record({
  'totalDeductions' : IDL.Float64,
  'netPayable' : IDL.Float64,
  'bonus' : IDL.Float64,
  'leaveDeduction' : IDL.Float64,
  'pfDeduction' : IDL.Float64,
  'baseSalary' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addEmployee' : IDL.Func([Employee], [], []),
  'approveLeaveRequest' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteEmployee' : IDL.Func([IDL.Text], [], []),
  'deleteLeaveRequest' : IDL.Func([IDL.Text], [], []),
  'getAllEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
  'getAllLeaves' : IDL.Func([], [IDL.Vec(LeaveRequest)], ['query']),
  'getAllPendingLeaves' : IDL.Func([], [IDL.Vec(LeaveRequest)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'getEmployee' : IDL.Func([IDL.Text], [Employee], ['query']),
  'getLeavesByEmployee' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(LeaveRequest)],
      ['query'],
    ),
  'getSalaryBreakdown' : IDL.Func(
      [IDL.Text, IDL.Text],
      [SalaryBreakdown],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'rejectLeaveRequest' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitContactForm' : IDL.Func([ContactSubmission], [], []),
  'submitLeaveRequest' : IDL.Func([LeaveRequest], [], []),
  'updateEmployee' : IDL.Func([IDL.Text, Employee], [], []),
  'updateLeaveRequest' : IDL.Func([IDL.Text, LeaveRequest], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Employee = IDL.Record({
    'name' : IDL.Text,
    'designation' : IDL.Text,
    'joiningDate' : IDL.Text,
    'totalLeaveBalance' : IDL.Nat,
    'email' : IDL.Text,
    'leavesTaken' : IDL.Nat,
    'employeeId' : IDL.Text,
    'linkedUserId' : IDL.Opt(IDL.Text),
    'bonus' : IDL.Float64,
    'department' : IDL.Text,
    'baseSalary' : IDL.Float64,
    'pfPercentage' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const LeaveStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const LeaveRequest = IDL.Record({
    'status' : LeaveStatus,
    'leaveId' : IDL.Text,
    'employeeName' : IDL.Text,
    'endDate' : IDL.Text,
    'days' : IDL.Nat,
    'submittedOn' : IDL.Text,
    'employeeId' : IDL.Text,
    'startDate' : IDL.Text,
    'reason' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'employeeId' : IDL.Opt(IDL.Text),
  });
  const ContactSubmission = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'submittedOn' : IDL.Text,
    'email' : IDL.Text,
    'company' : IDL.Text,
    'message' : IDL.Text,
  });
  const SalaryBreakdown = IDL.Record({
    'totalDeductions' : IDL.Float64,
    'netPayable' : IDL.Float64,
    'bonus' : IDL.Float64,
    'leaveDeduction' : IDL.Float64,
    'pfDeduction' : IDL.Float64,
    'baseSalary' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addEmployee' : IDL.Func([Employee], [], []),
    'approveLeaveRequest' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteEmployee' : IDL.Func([IDL.Text], [], []),
    'deleteLeaveRequest' : IDL.Func([IDL.Text], [], []),
    'getAllEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
    'getAllLeaves' : IDL.Func([], [IDL.Vec(LeaveRequest)], ['query']),
    'getAllPendingLeaves' : IDL.Func([], [IDL.Vec(LeaveRequest)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'getEmployee' : IDL.Func([IDL.Text], [Employee], ['query']),
    'getLeavesByEmployee' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(LeaveRequest)],
        ['query'],
      ),
    'getSalaryBreakdown' : IDL.Func(
        [IDL.Text, IDL.Text],
        [SalaryBreakdown],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'rejectLeaveRequest' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitContactForm' : IDL.Func([ContactSubmission], [], []),
    'submitLeaveRequest' : IDL.Func([LeaveRequest], [], []),
    'updateEmployee' : IDL.Func([IDL.Text, Employee], [], []),
    'updateLeaveRequest' : IDL.Func([IDL.Text, LeaveRequest], [], []),
  });
};

export const init = ({ IDL }) => { return []; };