/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactSubmission {
  'id' : string,
  'name' : string,
  'submittedOn' : string,
  'email' : string,
  'company' : string,
  'message' : string,
}
export interface Employee {
  'name' : string,
  'designation' : string,
  'joiningDate' : string,
  'totalLeaveBalance' : bigint,
  'email' : string,
  'leavesTaken' : bigint,
  'employeeId' : string,
  'linkedUserId' : [] | [string],
  'bonus' : number,
  'department' : string,
  'baseSalary' : number,
  'pfPercentage' : number,
}
export interface LeaveRequest {
  'status' : LeaveStatus,
  'leaveId' : string,
  'employeeName' : string,
  'endDate' : string,
  'days' : bigint,
  'submittedOn' : string,
  'employeeId' : string,
  'startDate' : string,
  'reason' : string,
}
export type LeaveStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface SalaryBreakdown {
  'totalDeductions' : number,
  'netPayable' : number,
  'bonus' : number,
  'leaveDeduction' : number,
  'pfDeduction' : number,
  'baseSalary' : number,
}
export interface UserProfile { 'name' : string, 'employeeId' : [] | [string] }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addEmployee' : ActorMethod<[Employee], undefined>,
  'approveLeaveRequest' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteEmployee' : ActorMethod<[string], undefined>,
  'deleteLeaveRequest' : ActorMethod<[string], undefined>,
  'getAllEmployees' : ActorMethod<[], Array<Employee>>,
  'getAllLeaves' : ActorMethod<[], Array<LeaveRequest>>,
  'getAllPendingLeaves' : ActorMethod<[], Array<LeaveRequest>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'getEmployee' : ActorMethod<[string], Employee>,
  'getLeavesByEmployee' : ActorMethod<[string], Array<LeaveRequest>>,
  'getSalaryBreakdown' : ActorMethod<[string, string], SalaryBreakdown>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'rejectLeaveRequest' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitContactForm' : ActorMethod<[ContactSubmission], undefined>,
  'submitLeaveRequest' : ActorMethod<[LeaveRequest], undefined>,
  'updateEmployee' : ActorMethod<[string, Employee], undefined>,
  'updateLeaveRequest' : ActorMethod<[string, LeaveRequest], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];