/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface LeaveRequest {
    status: LeaveStatus;
    leaveId: string;
    employeeName: string;
    endDate: string;
    days: bigint;
    submittedOn: string;
    employeeId: string;
    startDate: string;
    reason: string;
}
export interface SalaryBreakdown {
    totalDeductions: number;
    netPayable: number;
    bonus: number;
    leaveDeduction: number;
    pfDeduction: number;
    baseSalary: number;
}
export interface ContactSubmission {
    id: string;
    name: string;
    submittedOn: string;
    email: string;
    company: string;
    message: string;
}
export interface Employee {
    name: string;
    designation: string;
    joiningDate: string;
    totalLeaveBalance: bigint;
    email: string;
    leavesTaken: bigint;
    employeeId: string;
    linkedUserId?: string;
    bonus: number;
    department: string;
    baseSalary: number;
    pfPercentage: number;
}
export interface UserProfile {
    name: string;
    employeeId?: string;
}
export enum LeaveStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addEmployee(employee: Employee): Promise<void>;
    approveLeaveRequest(leaveId: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteEmployee(id: string): Promise<void>;
    deleteLeaveRequest(id: string): Promise<void>;
    getAllEmployees(): Promise<Array<Employee>>;
    getAllLeaves(): Promise<Array<LeaveRequest>>;
    getAllPendingLeaves(): Promise<Array<LeaveRequest>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getContactSubmissions(): Promise<Array<ContactSubmission>>;
    getEmployee(id: string): Promise<Employee>;
    getLeavesByEmployee(employeeId: string): Promise<Array<LeaveRequest>>;
    getSalaryBreakdown(employeeId: string, arg1: string): Promise<SalaryBreakdown>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    rejectLeaveRequest(leaveId: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitContactForm(submission: ContactSubmission): Promise<void>;
    submitLeaveRequest(request: LeaveRequest): Promise<void>;
    updateEmployee(id: string, updatedEmployee: Employee): Promise<void>;
    updateLeaveRequest(id: string, updatedRequest: LeaveRequest): Promise<void>;
}
import type { Employee as _Employee, LeaveRequest as _LeaveRequest, LeaveStatus as _LeaveStatus, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addEmployee(arg0: Employee): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addEmployee(to_candid_Employee_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEmployee(to_candid_Employee_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async approveLeaveRequest(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveLeaveRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveLeaveRequest(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteEmployee(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEmployee(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEmployee(arg0);
            return result;
        }
    }
    async deleteLeaveRequest(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLeaveRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLeaveRequest(arg0);
            return result;
        }
    }
    async getAllEmployees(): Promise<Array<Employee>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEmployees();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEmployees();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllLeaves(): Promise<Array<LeaveRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLeaves();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLeaves();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPendingLeaves(): Promise<Array<LeaveRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPendingLeaves();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPendingLeaves();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContactSubmissions(): Promise<Array<ContactSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContactSubmissions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContactSubmissions();
            return result;
        }
    }
    async getEmployee(arg0: string): Promise<Employee> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmployee(arg0);
                return from_candid_Employee_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmployee(arg0);
            return from_candid_Employee_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeavesByEmployee(arg0: string): Promise<Array<LeaveRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeavesByEmployee(arg0);
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeavesByEmployee(arg0);
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSalaryBreakdown(arg0: string, arg1: string): Promise<SalaryBreakdown> {
        if (this.processError) {
            try {
                const result = await this.actor.getSalaryBreakdown(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSalaryBreakdown(arg0, arg1);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async rejectLeaveRequest(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectLeaveRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectLeaveRequest(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n19(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n19(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitContactForm(arg0: ContactSubmission): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContactForm(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContactForm(arg0);
            return result;
        }
    }
    async submitLeaveRequest(arg0: LeaveRequest): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitLeaveRequest(to_candid_LeaveRequest_n21(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitLeaveRequest(to_candid_LeaveRequest_n21(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateEmployee(arg0: string, arg1: Employee): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEmployee(arg0, to_candid_Employee_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEmployee(arg0, to_candid_Employee_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateLeaveRequest(arg0: string, arg1: LeaveRequest): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLeaveRequest(arg0, to_candid_LeaveRequest_n21(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLeaveRequest(arg0, to_candid_LeaveRequest_n21(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_Employee_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Employee): Employee {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_LeaveRequest_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LeaveRequest): LeaveRequest {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_LeaveStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LeaveStatus): LeaveStatus {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _LeaveStatus;
    leaveId: string;
    employeeName: string;
    endDate: string;
    days: bigint;
    submittedOn: string;
    employeeId: string;
    startDate: string;
    reason: string;
}): {
    status: LeaveStatus;
    leaveId: string;
    employeeName: string;
    endDate: string;
    days: bigint;
    submittedOn: string;
    employeeId: string;
    startDate: string;
    reason: string;
} {
    return {
        status: from_candid_LeaveStatus_n12(_uploadFile, _downloadFile, value.status),
        leaveId: value.leaveId,
        employeeName: value.employeeName,
        endDate: value.endDate,
        days: value.days,
        submittedOn: value.submittedOn,
        employeeId: value.employeeId,
        startDate: value.startDate,
        reason: value.reason
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    employeeId: [] | [string];
}): {
    name: string;
    employeeId?: string;
} {
    return {
        name: value.name,
        employeeId: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.employeeId))
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    designation: string;
    joiningDate: string;
    totalLeaveBalance: bigint;
    email: string;
    leavesTaken: bigint;
    employeeId: string;
    linkedUserId: [] | [string];
    bonus: number;
    department: string;
    baseSalary: number;
    pfPercentage: number;
}): {
    name: string;
    designation: string;
    joiningDate: string;
    totalLeaveBalance: bigint;
    email: string;
    leavesTaken: bigint;
    employeeId: string;
    linkedUserId?: string;
    bonus: number;
    department: string;
    baseSalary: number;
    pfPercentage: number;
} {
    return {
        name: value.name,
        designation: value.designation,
        joiningDate: value.joiningDate,
        totalLeaveBalance: value.totalLeaveBalance,
        email: value.email,
        leavesTaken: value.leavesTaken,
        employeeId: value.employeeId,
        linkedUserId: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.linkedUserId)),
        bonus: value.bonus,
        department: value.department,
        baseSalary: value.baseSalary,
        pfPercentage: value.pfPercentage
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): LeaveStatus {
    return "pending" in value ? LeaveStatus.pending : "approved" in value ? LeaveStatus.approved : "rejected" in value ? LeaveStatus.rejected : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Employee>): Array<Employee> {
    return value.map((x)=>from_candid_Employee_n6(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LeaveRequest>): Array<LeaveRequest> {
    return value.map((x)=>from_candid_LeaveRequest_n10(_uploadFile, _downloadFile, x));
}
function to_candid_Employee_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Employee): _Employee {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_LeaveRequest_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeaveRequest): _LeaveRequest {
    return to_candid_record_n22(_uploadFile, _downloadFile, value);
}
function to_candid_LeaveStatus_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeaveStatus): _LeaveStatus {
    return to_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    designation: string;
    joiningDate: string;
    totalLeaveBalance: bigint;
    email: string;
    leavesTaken: bigint;
    employeeId: string;
    linkedUserId?: string;
    bonus: number;
    department: string;
    baseSalary: number;
    pfPercentage: number;
}): {
    name: string;
    designation: string;
    joiningDate: string;
    totalLeaveBalance: bigint;
    email: string;
    leavesTaken: bigint;
    employeeId: string;
    linkedUserId: [] | [string];
    bonus: number;
    department: string;
    baseSalary: number;
    pfPercentage: number;
} {
    return {
        name: value.name,
        designation: value.designation,
        joiningDate: value.joiningDate,
        totalLeaveBalance: value.totalLeaveBalance,
        email: value.email,
        leavesTaken: value.leavesTaken,
        employeeId: value.employeeId,
        linkedUserId: value.linkedUserId ? candid_some(value.linkedUserId) : candid_none(),
        bonus: value.bonus,
        department: value.department,
        baseSalary: value.baseSalary,
        pfPercentage: value.pfPercentage
    };
}
function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    employeeId?: string;
}): {
    name: string;
    employeeId: [] | [string];
} {
    return {
        name: value.name,
        employeeId: value.employeeId ? candid_some(value.employeeId) : candid_none()
    };
}
function to_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: LeaveStatus;
    leaveId: string;
    employeeName: string;
    endDate: string;
    days: bigint;
    submittedOn: string;
    employeeId: string;
    startDate: string;
    reason: string;
}): {
    status: _LeaveStatus;
    leaveId: string;
    employeeName: string;
    endDate: string;
    days: bigint;
    submittedOn: string;
    employeeId: string;
    startDate: string;
    reason: string;
} {
    return {
        status: to_candid_LeaveStatus_n23(_uploadFile, _downloadFile, value.status),
        leaveId: value.leaveId,
        employeeName: value.employeeName,
        endDate: value.endDate,
        days: value.days,
        submittedOn: value.submittedOn,
        employeeId: value.employeeId,
        startDate: value.startDate,
        reason: value.reason
    };
}
function to_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeaveStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == LeaveStatus.pending ? {
        pending: null
    } : value == LeaveStatus.approved ? {
        approved: null
    } : value == LeaveStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
